-- Auto-generated by shell -- DO NOT EDIT
hl.config({
    general = {
        col = {
            active_border   = "rgba(e95e5459)",
            inactive_border = "rgba(e95e5414)",
        },
    },
    misc = {
        background_color = "rgba(1b100eff)",
    },
})
