#!/bin/bash
# =============================================================================
# Wallpaper Switcher (Pywal)
# =============================================================================
# Called by Quickshell's Wallpapers service to apply a new wallpaper.
# This triggers pywal which generates color schemes for all connected apps.
#
# Color pipeline:
#   Wallpaper -> wal -i -> ~/.cache/wal/colors.{json,sh,css,...}
#   Quickshell watches colors.json via PywalThemeLoader.qml
#   kitty gets ~/.cache/wal/colors-kitty.conf (auto-included)
#   Material colors generated by generate_colors_material.py
#
# Usage:
#   switchwall.sh --image <path>           Apply wallpaper from image file
#   switchwall.sh --mode dark|light        Switch pywal dark/light theme
#   switchwall.sh                          Reset to last wallpaper

while [[ $# -gt 0 ]]; do
    case "$1" in
        --image)
            IMAGE="$2"
            shift 2
            ;;
        --mode)
            MODE="$2"
            shift 2
            ;;
        --noswitch)
            NOSWITCH=1
            shift
            ;;
        *)
            shift
            ;;
    esac
done

if [[ -n "$IMAGE" && -f "$IMAGE" ]]; then
    wal -i "$IMAGE" -q
elif [[ -n "$MODE" ]]; then
    wal --theme "$MODE" -q
else
    wal -R -q
fi
